version: "3.8"

services:
  psql-db:
    image: postgres
    container_name: psql-db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=mercadona
      - POSTGRES_HOST_AUTH_METHOD = trust
    ports:
      - '5431:5432'

  mercadona_app:
    container_name: mercadona_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8083:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/mercadona
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - psql-db